### ISSUE TITLE
Sensor stops reading information

### ISSUE THREAD

**Issue by JoseCaetanoNeto** [magic7s/intelbras-solar#9]
## Version of the custom_component
0.0.5

## Configuration

intelbras_solar:
  username: !secret intelbras_username
  password: !secret intelbras_password

## Describe the bug
sensor stops reading information. I need to perform a Home Assistant resertar to get back to working correctly.

## Debug log

2024-08-01 13:00:00.318 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.producao_solar_total_aldeia_casa fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1298, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/intelbras_solar/intelbras.py", line 149, in update
    self._state = self._get_plant_information()["eTotal"]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/intelbras_solar/intelbras.py", line 109, in _get_plant_information
    data = json.loads(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

2024-08-02 12:20:05.768 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.producao_solar_total_aldeia_casa fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 944, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1298, in async_device_update
    await hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/intelbras_solar/intelbras.py", line 149, in update
    self._state = self._get_plant_information()["eTotal"]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/intelbras_solar/intelbras.py", line 109, in _get_plant_information
    data = json.loads(response.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 3 column 1 (char 2)

**many lines of same log**

![image](https://github.com/user-attachments/assets/3d7cca82-aca6-4ac5-8e9a-6adf676b88ce)

![image](https://github.com/user-attachments/assets/51d3fc99-8ffb-47a2-9d8d-89e6ab7d425a)

**Comment by magic7s** [comment]
I had the same issue but a simple restart of HA this morning cleared it up.
